#!/bin/bash -e
#SBATCH --job-name=FastQC
#SBATCH --account=uoa02626
#SBATCH --time=72:00:00
#SBATCH --mem=36GB
#SBATCH --mail-user=nbhu117@aucklanduni.ac.nzan
#SBATCH --mail-type=ALL
#SBATCH --nodes=1
#SBATCH --cpus-per-task=18
#SBATCH -D /nesi/nobackup/uoa02626/admix/

BASEDIR=/nesi/nobackup/uoa02626/admix/input/ #TRANSFER FILES FROM pcangsd/angsd/

for fq1 in /nesi/nobackup/uoa02626/admix/input/*.beagle.gz
do
echo "working with file $fq1"

base=$(basename -s .beagle.gz $fq1) #check the final file created by angsd first.
echo "base name is $base"

fq1=/nesi/nobackup/uoa02626/admix/input/${base}.beagle.gz


/nesi/nobackup/uoa02626/admix/NGSadmix -likes $fq1 -K 3 -o outFileName -P 18

# -likes beagle file of genotype likelihoods
# -K number of clusters
# -o prefix of output file names
# -P Number of threads used

done
