#!/bin/bash -e
#SBATCH --job-name=FastQC
#SBATCH --account=uoa02626
#SBATCH --time=48:00:00
#SBATCH --mem=48GB
#SBATCH --mail-user=nbhu117@aucklanduni.ac.nz
#SBATCH --mail-type=ALL
#SBATCH --nodes=1
#SBATCH --cpus-per-task=18
#SBATCH -D /nesi/nobackup/uoa02626/pcangsd/beagle/testbeagle/


module load SAMtools/1.10-GCC-9.2.0
module load BEDTools/2.29.2-GCC-9.2.0
module load GCCcore/5.4.0
#module load angsd/0.923-gimkl-2017a
module load Python-Geo/3.8.2-gimkl-2020a

BAMLIST=/nesi/nobackup/uoa02626/pcangsd/beagle/bam.filelist
BASEDIR=/nesi/nobackup/uoa02626/pcangsd/
BAMDIR=${BASEDIR}/
REFDIR=/nesi/nobackup/uoa02626/results/GCF_004348235.1_GSC_HSeal_1.0_genomic.fna
OUTDIR=${BASEDIR}/beagle/testbeagle

#for a1 in  ${BAMLIST}
#do

/nesi/nobackup/uoa02626/pcangsd/angsd/angsd -GL 2 -b ${BAMLIST} -out ${OUTDIR}/A1_genolike -nThreads 18 -doGlf 2 -doMajorMinor 1 -SNP_pval 1e-6 -doMaf 1

/nesi/nobackup/uoa02626/pcangsd/angsd/angsd -b ${BAMLIST} -anc ${REFDIR} -out ${OUTDIR}/A1.angsd -minMapQ 30 -minQ 20 -doMaf 1 -minMaf 0.05 -SNP_pval 2e-6 -GL 2 -doGlf 2 -doMajorMinor 1 -doPost 1

gunzip -c ${BAMLIST} | cut -f 1,2,3,4 | tail -n +2 > ${OUTDIR}/A1_SNPs.txt

/nesi/nobackup/uoa02626/pcangsd/angsd/angsd sites index ${OUTDIR}/A1_SNPs.txt

SNPLIST=${OUTDIR}/A1_SNPs.txt

/nesi/nobackup/uoa02626/pcangsd/angsd/angsd -b ${BAMLIST} -anc ${REFDIR} -out ${OUTDIR}/A1_SNPs \
        -GL 2 -doGlf 2 -doMajorMinor 3 -doMAF 1 -doPost 1 -doIBS 1 -doCounts 1 -doCov 1 -makeMatrix 1 -sites ${SNPlist}

#done


