#!/bin/bash -e
#SBATCH --job-name=FastQC 
#SBATCH --account=uoa02626 
#SBATCH --time=24:00:00      
#SBATCH --mem=3GB          
#SBATCH --mail-user=nbhu117@aucklanduni.ac.nz  
#SBATCH --mail-type=ALL 
#SBATCH --nodes=1 
#SBATCH --cpus-per-task=1 
#SBATCH -D /nesi/nobackup/uoa02626/harbour_seals 

module load FastQC/0.11.9  

fastqc */*.fastq*
