#!/bin/bash -e
#SBATCH --job-name=FastQC
#SBATCH --account=uoa02626
#SBATCH --time=72:00:00
#SBATCH --mem=36GB
#SBATCH --mail-user=nbhu117@aucklanduni.ac.nz
#SBATCH --mail-type=ALL
#SBATCH --nodes=1
#SBATCH --cpus-per-task=18
#SBATCH -D /nesi/nobackup/uoa02626/results/merge_bam/

module load GATK/4.1.8.1-gimkl-2020a
module load SAMtools/1.10-GCC-9.2.0


BAMLIST=/nesi/nobackup/uoa02626/results/merge_bam/*_sorted_dedup_overlapclipped.bam

REFERENCE=/nesi/nobackup/uoa02626/results/GCF_004348235.1_GSC_HSeal_1.0_genomic.fna.gz 

REFNAME=indel_aligned 

for SAMPLEBAM in  $BAMLIST
do
base=$(basename -s .merge.sorted.bam $SAMPLEBAM)

samtools index ${SAMPLEBAM}

gatk
-T RealignerTargetCreator \
-R ${REFERENCE} \
-I ${BAMLIST} \
-o /nesi/nobackup/uoa02626/results/merge_bam/${base}.all_samples_for_indel_realigner.intervals \
-drf BadMate

gatk
-T IndelRealigner \
-R ${REFERENCE} \
-I ${BAMLIST} \
-targetIntervals /nesi/nobackup/uoa02626/results/merge_bam/${base}.all_samples_for_indel_realigner.intervals \
--consensusDeterminationModel USE_READS  \
--nWayOut _realigned.bam

done
