#!/bin/bash -e
#SBATCH --job-name=Trimmomatic 
#SBATCH --account=uoa02626 
#SBATCH --time=24:00:00      
#SBATCH --mem=3GB          
#SBATCH --mail-user=nbhu117@aucklanduni.ac.nz  
#SBATCH --mail-type=ALL 
#SBATCH --nodes=1 
#SBATCH --cpus-per-task=4
#SBATCH -D /nesi/nobackup/uoa02626/harbour_seals 

module load Trimmomatic/0.39-Java-1.8.0_144


for infile in */*R1_001.fastq.gz;
do 
base=$(basename ${infile} .fastq.gz); 
R2=`echo $infile | sed 's/R1/R2/g'`;
echo $infile $R2 $base;
trimmomatic PE -threads 4 $infile $R2 \
${base}.1.trim.fastq.gz ${base}.1.un.trim.fastq.gz \
${base}.2.trim.fastq.gz ${base}.2.un.trim.fastq.gz \
SLIDINGWINDOW:4:20 MINLEN:25 ILLUMINACLIP: /opt/nesi/CS400_centos7_bdw/Trimmomatic/0.39-Java-1.8.0_144/adapters/NexteraPE-PE.fa
done
