#!/bin/bash -e
#SBATCH --job-name=FastQC
#SBATCH --account=uoa02626
#SBATCH --time=72:00:00
#SBATCH --mem=36GB
#SBATCH --mail-user=nbhu117@aucklanduni.ac.nz
#SBATCH --mail-type=ALL
#SBATCH --nodes=1
#SBATCH --cpus-per-task=18
#SBATCH -D /nesi/nobackup/uoa02626/harbour_seals

module load BWA/0.7.17-GCC-9.2.0

module load SAMtools/1.10-GCC-9.2.0

module load VCFtools/0.1.15-GCC-9.2.0-Perl-5.30.1

module load BCFtools/1.10.2-GCC-9.2.0

genome=/nesi/nobackup/uoa02626/results/GCF_004348235.1_GSC_HSeal_1.0_genomic.fna

bwa index $genome

for fq1 in /nesi/nobackup/uoa02626/harbour_seals/*.trim.fastq.gz
do

sed -i 's/\(^@.*\):2:/\1:1:/g' /nesi/nobackup/uoa02626/harbour_seals/*.2.trim.fastq.gz
Done

echo "working with file $fq1"

base=$(basename -s .1.trim.fastq.gz $fq1)
echo "base name is $base"

    fq1=/nesi/nobackup/uoa02626/harbour_seals/${base}.1.trim.fastq.gz
    fq2=/nesi/nobackup/uoa02626/harbour_seals/${base}.2.trim.fastq.gz
    sam=/nesi/nobackup/uoa02626/results/sam/${base}.aligned.sam
    bam=/nesi/nobackup/uoa02626/results/bam/${base}.aligned.bam
    sorted_bam=/nesi/nobackup/uoa02626/results/bam/${base}.aligned.sorted.bam
    raw_bcf=/nesi/nobackup/uoa02626/results/bcf/${base}_raw.bcf
    variants=/nesi/nobackup/uoa02626/results/bcf/${base}_variants.vcf
    final_variants=/nesi/nobackup/uoa02626/results/vcf/${base}_final_variants.vcf

    bwa mem -t 18 $genome $fq1 $fq2 > $sam
    samtools view -S -b -@ 18 $sam > $bam
    samtools sort -@ 18 -o $sorted_bam $bam
    samtools index -@ 18 $sorted_bam
    bcftools mpileup --threads 18 -O b -o $raw_bcf -f $genome $sorted_bam
    bcftools call --threads 18 -m -v -o $variants $raw_bcf
    vcfutils.pl varFilter $variants > $final_variants

done
